import * as http2 from 'http2';
import { IInstance, Plugin } from '../application';
import type { ContentType, HttpServerOptions, TLSOptions, TokenConfig } from './types';
import { Component } from '../core';
declare class HttpServer implements Plugin {
    readonly tls: TLSOptions;
    readonly port: number;
    readonly host: string;
    readonly requestTimeout: number;
    readonly maxSessions: number;
    readonly bodyLimit: number;
    readonly contentType: ContentType[];
    readonly name = "HttpServer";
    readonly components: Component<any, any>[];
    static factory(options: HttpServerOptions): HttpServer;
    private activeSessions;
    private handlers;
    private server;
    readonly primaryContentTyp: ContentType;
    private routing;
    private runCommand;
    private handleRequest;
    private readonly accessJwtService;
    private readonly refreshJwtService;
    private security;
    constructor(tls: TLSOptions, accessTokenConfig: TokenConfig, refreshTokenConfig: TokenConfig, port?: number, host?: string, requestTimeout?: number, maxSessions?: number, bodyLimit?: number, contentType?: ContentType[]);
    private constructorHttp2;
    private constructorJwtService;
    private publicTokenService;
    init(instance: IInstance): any;
    onSession(session: http2.ServerHttp2Session): void;
}
export { HttpServer };
