import * as vm from 'node:vm';
declare class CodeError extends Error {
}
declare class Code<T = Object> {
    source: string;
    name: string;
    dirname: any;
    relative: string;
    private runOptions;
    path: string;
    require: {
        (modulePath: string, extra?: Object): any;
    };
    import: {
        (specifier: string): Promise<any>;
    };
    context: vm.Context;
    type: number;
    exports: T | null;
    constructor(source: string, name: string, type?: CodeTypeValue | number, requireFrom?: (modulePath: string) => any, importFrom?: {
        (specifier: string): Promise<any>;
    }, dirname?: any, relative?: string, pathTo?: any, context?: Record<string, any>, runOptions?: vm.RunningScriptOptions);
    load(): unknown;
    private loadCommonJS;
    private exportCommon;
    private loadESM;
    private loadTS;
    private definitionType;
    private detectESMSyntax;
    private requireDependency;
    private requireDependencyAsync;
    private esmLinker;
    static supportExtension: any;
}
declare const DEFAULT_CONTEXT: {
    AbortController: any;
    AbortSignal: any;
    Event: any;
    EventTarget: any;
    MessageChannel: any;
    MessageEvent: any;
    MessagePort: any;
    Buffer: any;
    Blob: any;
    FormData: any;
    Headers: any;
    Response: any;
    Request: any;
    ByteLengthQueuingStrategy: any;
    URL: any;
    URLSearchParams: any;
    TextDecoder: any;
    TextEncoder: any;
    TextDecoderStream: any;
    TextEncoderStream: any;
    WebAssembly: any;
    queueMicrotask: any;
    setTimeout: any;
    setImmediate: any;
    setInterval: any;
    clearTimeout: any;
    clearImmediate: any;
    clearInterval: any;
    BroadcastChannel: any;
    CompressionStream: any;
    DecompressionStream: any;
    CountQueuingStrategy: any;
    fetch: any;
};
declare const NODE_CONTEXT: {
    global: any;
    process: any;
    console: any;
    AbortController: any;
    AbortSignal: any;
    Event: any;
    EventTarget: any;
    MessageChannel: any;
    MessageEvent: any;
    MessagePort: any;
    Buffer: any;
    Blob: any;
    FormData: any;
    Headers: any;
    Response: any;
    Request: any;
    ByteLengthQueuingStrategy: any;
    URL: any;
    URLSearchParams: any;
    TextDecoder: any;
    TextEncoder: any;
    TextDecoderStream: any;
    TextEncoderStream: any;
    WebAssembly: any;
    queueMicrotask: any;
    setTimeout: any;
    setImmediate: any;
    setInterval: any;
    clearTimeout: any;
    clearImmediate: any;
    clearInterval: any;
    BroadcastChannel: any;
    CompressionStream: any;
    DecompressionStream: any;
    CountQueuingStrategy: any;
    fetch: any;
};
declare const CodeType: any;
type CodeTypeValue = keyof typeof CodeType;
export { CodeType, Code, CodeError, NODE_CONTEXT, DEFAULT_CONTEXT, CodeTypeValue };
